targets:
  $default:
    sources:
      - openapi_specs/**
      - lib/**
      - $package$
    builders:
      # disable auto_mappr when updating openapi specs
      # auto_mappr:
      #   enabled: false
      chopper_generator:
        options:
          header: "// Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "openapi_specs/"
          output_folder: "lib/src/service/openapi_generated_code/"
          input_urls:
            - url: https://raw.githubusercontent.com/Kareadita/Kavita/v0.8.0/openapi.json
              file_name: kavita_api_v1.json
          include_if_null: false
          override_equals_and_hashcode: true
          override_to_string: true
          response_override_value_map:
            - url: "/api/Users/myself"
              method: get
              overridden_value: "MemberDto"
