targets:
  $default:
    sources:
      - openapi_specs/**
      - lib/**
      - $package$
    builders:
      chopper_generator:
        options:
          header: "// Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "openapi_specs/"
          output_folder: "lib/src/openapi_generated_code/"
          input_urls:
            - url: https://raw.githubusercontent.com/Kareadita/Kavita/develop/openapi.json
              file_name: kavita_api.json
          include_if_null: false
          default_values_map:
            - type_name: String
              default_value: ""
          override_equals_and_hashcode: true
          override_to_string: true
