name: kavita_api
description: Unnoficial Kavita API Client for Dart applications
version: 1.0.0
repository: https://github.com/getBoolean/subete_app
homepage: https://subete.dev
issue_tracker: https://github.com/getBoolean/subete_app/issues

environment:
  sdk: ^3.3.0

dependencies:
  chopper: ^7.1.1
  collection: ^1.18.0
  http: ^1.2.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  chopper_generator: ^7.1.1
  dotenv: ^4.2.0
  json_serializable: ^6.7.1
  lints: ^3.0.0
  swagger_dart_code_generator: ^2.15.0
  test: ^1.24.0
