name: kavita_api
description: Unnoficial Kavita API Client for Dart applications
version: 0.0.1
repository: https://github.com/getBoolean/subete_app
homepage: https://subete.dev
issue_tracker: https://github.com/getBoolean/subete_app/issues

environment:
  sdk: ^3.3.0

dependencies:
  collection: ^1.0.0
  dart_mappable: ^4.0.0
  meta: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.8
  dart_mappable_builder: ^4.2.0
  dotenv: ^4.2.0
  lints: ^3.0.0
  mocktail: ^1.0.3
  test: ^1.24.0
